server:
  port: 9000

spring:
  application:
    name: oauth-authorization-server
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
